import sys
sys.path.append("../")
# from collections import Counter
# from itertools import chain
# from typing import List
# import pandas as pd
# import json
# import csv

# import matplotlib.pyplot as plt

import numpy as np
import cv2
import os
import imageio
from torch.utils.data import Dataset
import utils.config as cfg

DATA_PATH = cfg.DATA_PATH #path to data stored
NUM_TRAIN = 700
NUM_TEST = 200
NUM_VAL = 100


class toyScenesdata(Dataset):

    def __init__(self, set_name="train", agents = 2, traj_time="2.5"):        

        self.set_name = set_name
        self.traj_time = ("", "_"+str(traj_time))[str(traj_time) != "2.5"]

        assert(self.set_name in ["train", "test", "val"])
#         print("Reading from ", DATA_PATH+str(agents)+"/")
        self.DATA_PATH = cfg.DATA_PATH+str(agents)+"/"
        #read the scenes and trajectory arrays generated by the toy dataset
        self.scenes = os.listdir(self.DATA_PATH)
        print("Read in %d " % (len(self.scenes)))

        #get the training set
        self.train_scenes = list(map(self.scenes.__getitem__,range(0,NUM_TRAIN)))
        print(len(self.train_scenes))

        #get test set        
        self.test_scenes = list(map(self.scenes.__getitem__, range(NUM_TRAIN, NUM_TRAIN+NUM_TEST)))
        print(len(self.test_scenes))

        #get val set        
        self.val_scenes = list(map(self.scenes.__getitem__, range(NUM_TRAIN+NUM_TEST, NUM_TEST+NUM_TRAIN+NUM_VAL)))
        print(len(self.val_scenes))
        
        

    def __len__(self):
        if self.set_name == "train":
            return len(self.train_scenes)
    
        if self.set_name == "test":
            return len(self.test_scenes)
    
        if self.set_name == "val":
            return len(self.val_scenes)

    def __getitem__(self, test_idx):
        
        #get the scene
        if self.set_name == "train":
            scene = self.train_scenes[test_idx]        
    
        if self.set_name == "test":
            scene = self.test_scenes[test_idx]        
    
        if self.set_name == "val":
            scene = self.val_scenes[test_idx]        
                

        coords = np.load(self.DATA_PATH+scene+"/ls.npy", allow_pickle=True)
        env_map = np.array(cv2.imread(self.DATA_PATH+scene+"/scene"+self.traj_time+".png"))
        gt = np.array(list(np.array(np.load(self.DATA_PATH+scene+"/init.npy", allow_pickle=True))))
        count = 0

        #Initialise dictionary for returning data
        # print(gt)
        output_data = {"map":env_map, "coords":coords, "ground_truth":gt}

        return output_data
